---
title: "IE360 PROJECT SPRING 2024"
output: 
    html_document:
        toc: true
        toc_depth: 2
        number_sections: true
        toc_float: true
        code_folding: hide
        fig_caption: yes
date: "2024-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ayşe Sena Yeşilova, Eylül Rana Saraç, Uygar Şahin

# 1. Library Imports, gathering data

```{r}
require(forecast)
require(data.table)
require(lubridate)
require(ggplot2)
require(dplyr)


tday=today("Turkey")
data_path = getwd()
print(getwd())
weather_path = file.path(data_path, 'processed_weather')
production_path = file.path(data_path, 'production')
print(weather_path)


file_weather =  file.path(weather_path,'processed_weather.csv')
print(file_weather)
file_production =  file.path(production_path,'production.csv')

weather_data = fread(file_weather)
prod_data = fread(file_production)

weather_data = fread(file_weather)
production_data = fread(file_production)

# getting full weather date and hours as a template
template_dt = unique(weather_data[,list(date,hour)])
template_dt = merge(template_dt,production_data,by=c('date','hour'),all.x=T)
template_dt = template_dt[date<=(tday + 1)]







head(template_dt)

```

```{r}
long_weather = melt(weather_data,id.vars=c(1:4))

hourly_region_averages = dcast(long_weather, date+hour~variable,fun.aggregate=mean)
template_dt_with_weather = merge(template_dt,hourly_region_averages,by=c('date','hour'),all.x=T)

template_dt_with_weather = template_dt_with_weather[order(date,hour)]

available_data = template_dt_with_weather[!is.na(production)]
to_be_forecasted = template_dt_with_weather[is.na(production)]

template_dt_with_weather$datetime <- as.POSIXct(paste(template_dt_with_weather$date, template_dt_with_weather$hour), format="%Y-%m-%d %H")

available_data = template_dt_with_weather[!is.na(production)]
to_be_forecasted = template_dt_with_weather[is.na(production)]

data_r <- template_dt_with_weather


```

# 2. checking the time series, descriptive analysis

```{r}

ggplot(template_dt_with_weather, aes(x = datetime,y = production))  +
    
    geom_line()                                 +
    
    xlab("Date")                                +
    
    ylab("Production (in MwH)")


```
# 3. hourly production averages

```{r}
round(aggregate(available_data$production, list(available_data$hour), FUN = mean), 4)
```
# 3.Model 1 - Critical Hours

```{r}
template_dt_with_weather$hour <- as.numeric(template_dt_with_weather$hour)


template_dt_with_weather$datetime <- as.POSIXct(template_dt_with_weather$datetime)


critical_hours <- template_dt_with_weather %>%
  filter(hour %in% c(5, 6, 19))

# Plotting
critical_hours %>%
  ggplot(aes(x = datetime, y = production, group = factor(hour), color = factor(hour))) +
  geom_line() +
  scale_color_manual(name = "Hour",
                     labels = c("5 AM", "6 AM", "7 PM"),
                     values = c("#E64B35B2", "#3C5488B2", "#3E8543")) +
  xlab("Date") +
  ylab("Production") +
  theme_minimal() +
  theme(legend.position = "top") +
  scale_y_continuous(expand = c(0, 0)) 

critical_hours_7pm <- critical_hours %>%
  filter(hour == 19)


critical_hours_7pm %>%
  ggplot(aes(x = datetime, y = production, group = factor(hour), color = factor(hour))) +
  geom_line() +
  scale_color_manual(name = "Hour",
                     labels = c("7 PM"),
                     values = c("#3E8543")) +
  xlab("Date") +
  ylab("Production") +
  theme_minimal() +
  theme(legend.position = "top") +
  scale_y_continuous(expand = c(0, 0))
#there are some amount of production at 7pm for a few days

```

```{r hour-based, fig.show="hold", out.width="50%"}
usual_hours         <- template_dt_with_weather %>%
    
    filter(!hour %in% c(0, 1, 2, 3, 4,
                        5, 6, 19, 20,
                        21, 22, 23))

usual_hours$hour    <- as.factor(usual_hours$hour)

# Plot
usual_hours %>%
  ggplot(aes(x = datetime, y = production, group = factor(hour), color = factor(hour))) +
  geom_line() +
  xlab("Date") +
  ylab("Production") +
  theme_minimal() +
  theme(legend.position = "top") +
  scale_y_continuous(expand = c(0, 0)) 




```
```{r}
# Critical hours identifying non-zero months and weeks

# 5

five_am_nonzero <- critical_hours %>%
    
    filter(hour == "5" & production != 0)

five_am_nonzero_months <- unique(month(five_am_nonzero$datetime))

# 6

six_am_nonzero <- critical_hours %>%
    
    filter(hour == "6" & production != 0)

six_am_nonzero_weeks <- unique(week(six_am_nonzero$datetime))

# 19

seven_pm_nonzero <- critical_hours %>%
    
    filter(hour == "19" & production != 0)

seven_pm_nonzero_weeks <- unique(week(seven_pm_nonzero$datetime))

```


```{r critical-hours-five-am, fig.show="hold", out.width="50%"}

# Models for critical hours

# 5 O'Clock

five_am <- critical_hours %>%
    
    filter(hour == "5")
    
five_am <- subset(five_am, select = -c(hour))
    
# Is in nonzero period? If so, insert the # of the month, else, insert "No".

five_am$is_in_nzp       <- ifelse(month(five_am$datetime) %in% five_am_nonzero_months,
                                  as.factor(month(five_am$datetime)),
                                  "No")

model_five_am <- lm(production~. -datetime,
                    data = five_am)

checkresiduals(model_five_am$residuals)

```

```{r 5-am-lagged, fig.show="hold", out.width="50%"}

five_am$three_days_lag  <- usual_hours[,.(three_days_lag = shift(five_am$production, 
                                                                 n = 3L, 
                                                                 fill = NA, 
                                                                 type = "shift"))]

model_five_am <- lm(production~. -datetime,
                    data = five_am) 

summary(model_five_am)

checkresiduals(model_five_am$residuals)
```

```{r critical-hours-six-am, fig.show="hold", out.width="50%"}

# 6 O'Clock

six_am <- critical_hours %>%
    
    filter(hour == "6")
    
six_am <- subset(six_am, select = -c(hour))

six_am$is_in_nzp <- ifelse(week(six_am$datetime) %in% six_am_nonzero_weeks, 
                           as.factor(week(six_am$datetime)), 
                           "No")

six_am$three_days_lag <- usual_hours[,.(three_days_lag = shift(six_am$production, 
                                                               n = 3L, 
                                                               fill = NA, 
                                                               type = "shift"))]

model_six_am <- lm(production~. -datetime,
                   data = six_am) 

summary(model_six_am)

checkresiduals(model_six_am$residuals)

```

```{r critical-hours-eight-pm, fig.show="hold", out.width="50%"}

# 19 O'Clock

seven_pm <- critical_hours %>%
    
    filter(hour == "19")
    
seven_pm <- subset(seven_pm, select = -c(hour))

seven_pm$is_in_nzp <- ifelse(week(seven_pm$datetime) %in% seven_pm_nonzero_weeks, 
                             as.factor(week(seven_pm$datetime)), 
                             "No")

seven_pm$three_days_lag <- usual_hours[,.(three_days_lag = shift(seven_pm$production, 
                                                                 n = 3L, 
                                                                 fill = NA, 
                                                                 type = "shift"))]
    
model_seven_pm <- lm(production~. -datetime,
                     data = seven_pm) 

summary(model_seven_pm)

checkresiduals(model_seven_pm$residuals)

```


```{r predictions-five-am}
threedaysago = Sys.Date() -3
# Prediction 5

pred5 <- template_dt_with_weather
pred5$is_in_nzp <- ifelse(month(pred5$datetime) %in% five_am_nonzero_months,
                          as.factor(month(pred5$datetime)),
                          "No")

pred5 <- subset(pred5, select = -c(hour))

five_am_3hrslag <- rbind(five_am,
                     pred5[pred5$datetime == as.POSIXct(paste(threedaysago, "08:00:00"))], 
                     fill = TRUE)

five_am_3hrslag$three_days_lag <- five_am_3hrslag[,.(three_days_lag = shift(five_am_3hrslag$production, 
                                                                    n = 3L, 
                                                                    fill = NA, 
                                                                    type = "shift"))]

five_am_3hrslag$predictions <- predict(model_five_am, five_am_3hrslag)

results5 <- subset(five_am_3hrslag, select = c("production", "datetime", "predictions"))

```

```{r predicitions-six-am}

# Prediction 6

pred6 <- template_dt_with_weather
pred6$is_in_nzp <- ifelse(week(pred6$datetime) %in% six_am_nonzero_weeks,
                         as.factor(week(pred6$datetime)),
                         "No")

pred6 <- subset(pred6, select = -c(hour))

six_am_3hrslag <- rbind(six_am, pred6[pred6$datetime == as.POSIXct(paste(threedaysago, "09:00:00"))], fill = TRUE)

six_am_3hrslag$three_days_lag      <- six_am_3hrslag[,.(three_days_lag = shift(six_am_3hrslag$production, 
                                                                       n = 3L, 
                                                                       fill = NA, 
                                                                       type = "shift"))]

six_am_3hrslag$predictions <- predict(model_six_am, six_am_3hrslag)

results6 <- subset(six_am_3hrslag, select = c("production", "datetime", "predictions"))

```

```{r predictions-seven-pm}

# Prediction 19

pred19 <- template_dt_with_weather

pred19$is_in_nzp <- ifelse(week(pred19$datetime) %in% seven_pm_nonzero_weeks,
                           as.factor(week(pred19$datetime)),
                           "No")

pred19 <- subset(pred19, select = -c(hour))

seven_pm_3hrslag <- rbind(seven_pm, pred19[pred19$datetime == as.POSIXct(paste(threedaysago, "22:00:00"))], fill = TRUE)

seven_pm_3hrslag$three_days_lag <- seven_pm_3hrslag[,.(three_days_lag = shift(seven_pm_3hrslag$production, 
                                                                      n = 3L, 
                                                                      fill = NA, 
                                                                      type = "shift"))]

seven_pm_3hrslag$predictions <- predict(model_seven_pm, seven_pm_3hrslag)

results19 <- subset(seven_pm_3hrslag, select = c("production", "datetime", "predictions"))

```

```{r hours-and-months}
# Model for regular hours

data_r[,hour:=hour(datetime)]
data_r[,month:=month(datetime)]

train_data <- copy(data_r)
train_data <- train_data %>% 
    filter((train_data$hour < 19) & (train_data$hour > 6))

train_data$hour     <- as.factor(train_data$hour)
train_data$month    <- as.factor(train_data$month)
```


```{r usual-hours-model}

model_regular <- lm(production~. -datetime, train_data) 

summary(model_regular)

```

```{r fig.show="hold", out.width="50%"}

checkresiduals(model_regular$residuals)

acf(model_regular$residuals, 36)

```

```{r}

# added 72 hour lagged production as a predictor (not 24 hour because the data is restricted)

train_data$yesterday_prod <- train_data[ , .(yesterday_prod = shift(train_data$production,
                                                                    n = 36L,
                                                                    fill = NA))]

#data$yesterday_1lag_prod = data[,.(yesterday_prod = shift(data$production, n=24L, fill=NA))]

model_regular <- lm(production~. -datetime, train_data)

summary(model_regular)

```

```{r fig.show="hold", out.width="50%"}

checkresiduals(model_regular$residuals)
acf(model_regular$residuals, 2400)

```

```{r}

real_data <- template_dt_with_weather

real_data$yesterday_prod <- real_data[ , .(yesterday_prod = shift(real_data$production,
                                                                  n = 72L,
                                                                  fill = NA))]

real_data <- real_data %>% filter((real_data$hour < 18) & (real_data$hour > 6))

head(real_data)

```

```{r predictions}

input_data <- (real_data[date(real_data$date) == "2024-05-28"])

input_data$yesterday_prod   <- real_data[date(real_data$date) == "2024-05-27"]$production

input_data$hour             <- as.factor(input_data$hour)

input_data$month            <- as.factor(month((input_data$datetime)))

predictions                 <- input_data[ , predictions:= predict(model_regular,
                                                                   input_data)      ]

```

```{r predictions-vs-real, , fig.show="hold", out.width="50%"}

# Data for the predictions vs real data plot

data_pr_p           <- template_dt_with_weather

data_pr_p$hour      <- as.factor(data_pr_p$hour)

data_pr_p$month     <- as.factor(month((data_pr_p$datetime)))

data_pr_p$yesterday_prod <- data_pr_p[ , .(yesterday_prod = shift(data_pr_p$production,
                                                                  n = 72L,
                                                                  fill = NA))]

reg_train <- data_pr_p[data_pr_p$hour %in% c("7", "8", "9", "10",
                                            "11", "12", "13", "14",
                                            "15", "16", "17", "18"), ]

reg_train$predicted <- predict(model_regular, reg_train)

regular_results     <- subset(reg_train, select = c(datetime,
                                                    predicted))

data_pr_p <- left_join( x   = data_pr_p,
                        y   = results5[ ,-1],
                        by  = "datetime"    )

data_pr_p <- left_join( x   = data_pr_p,
                        y   = results6[ ,-1],
                        by  = "datetime"    )

data_pr_p <- left_join( x   = data_pr_p,
                        y   = results19[ ,-1],
                        by  = "datetime"        )

data_pr_p <- left_join( x   = data_pr_p,
                        y   = regular_results,
                        by  = "datetime"        )

data_pr_p$predictions <- coalesce(  data_pr_p$predictions.x,
                                    data_pr_p$predictions.y,
                                    data_pr_p$predictions,
                                    data_pr_p$predicted     )

data_pr_p[data_pr_p$hour %in% c("0", "1", "2", "3", "4",
                                "20", "21", "22", "23"),
          c("predicted")]                                   <- 0

data_pr_p[data_pr_p$predicted < 0, c("predicted")]          <- 0

ggplot(data_pr_p, aes(x = datetime)     )   +
    
    geom_line(aes(y = production,
                  color='real',
                  group = 1)            )   + 
    
    geom_line(aes(y = predicted,
                  color = 'predictions',
                  group = 1)            )   +
    
    xlab("Date")                            +
    
    ylab("Production")

```


$~$
```{r}
#critical hours 
today <- Sys.Date()
tomorrow <- today + 1

tomorrow_5am <- as.POSIXct(paste(tomorrow, "05:00:00"))
tomorrow_6am <- as.POSIXct(paste(tomorrow, "06:00:00"))
tomorrow_7pm <- as.POSIXct(paste(tomorrow, "19:00:00"))

# extracted the predictions for tomorrow critical hours
prediction_value5am <- results5[datetime == tomorrow_5am, predictions]
prediction_value6am <- results6[datetime == tomorrow_6am, predictions]
prediction_value7pm <- results19[datetime == tomorrow_7pm, predictions]





```


```{r}

#predictions for tomorrow (regular)
filtered_results <- regular_results %>%
  filter(as.Date(datetime) == today + 1) %>%
  mutate(predicted = sprintf("%.4f", predicted))


predicted_values_regular <- paste(filtered_results$predicted, collapse = ",")


```
`
```

```


